/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aula_17_10;
    
/**
 *
 * @author KAUAVICTORWEBER
 */
public class telaInicial extends javax.swing.JFrame {
    /**
     * Creates new form telaInicial
     */
    public telaInicial() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        outroNumero = new javax.swing.JTextField();
        btnSomar = new javax.swing.JButton();
        results = new javax.swing.JLabel();
        btnSubtrair = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(255, 255, 255));

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Calculadora Simples");

        numero.setText("Digite um numero...");
        numero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numeroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numeroFocusLost(evt);
            }
        });

        outroNumero.setText("Digite outro numero...");
        outroNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                outroNumeroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                outroNumeroFocusLost(evt);
            }
        });

        btnSomar.setBackground(new java.awt.Color(102, 204, 255));
        btnSomar.setForeground(new java.awt.Color(0, 0, 0));
        btnSomar.setText("Somar");
        btnSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomarActionPerformed(evt);
            }
        });

        results.setForeground(new java.awt.Color(0, 0, 0));
        results.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        results.setText("RESULTADO:");

        btnSubtrair.setBackground(new java.awt.Color(102, 204, 255));
        btnSubtrair.setForeground(new java.awt.Color(0, 0, 0));
        btnSubtrair.setText("Subtrair");
        btnSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtrairActionPerformed(evt);
            }
        });

        btnDividir.setBackground(new java.awt.Color(102, 204, 255));
        btnDividir.setForeground(new java.awt.Color(0, 0, 0));
        btnDividir.setText("Dividir");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });

        btnMultiplicar.setBackground(new java.awt.Color(102, 204, 255));
        btnMultiplicar.setForeground(new java.awt.Color(0, 0, 0));
        btnMultiplicar.setText("Multiplicar");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(btnSomar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(results)
                                    .addComponent(btnSubtrair))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDividir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMultiplicar))
                            .addComponent(outroNumero)
                            .addComponent(numero)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(titulo)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(outroNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSomar)
                    .addComponent(btnSubtrair)
                    .addComponent(btnDividir)
                    .addComponent(btnMultiplicar))
                .addGap(32, 32, 32)
                .addComponent(results)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomarActionPerformed
        //System.out.println("botao clicado");
        // Para pegar o texto de algum campo, usamos o metodo nomeDoComponente.getText();
        String numero1 = numero.getText();
        String numero2 = outroNumero.getText();
        
        // O método Integer.parseInt() converte um numero em String para int
        int numero1Int = Integer.parseInt(numero1);
        int numero2Int = Integer.parseInt(numero2);
        
        int soma = numero1Int + numero2Int;
        // Para trocar o texto de algum componente, usamos o método nomeDoComponente.setText("novo texto")
        results.setText("Resultado: " + soma);
    }//GEN-LAST:event_btnSomarActionPerformed

    private void numeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroFocusGained
        // Se o texto do campo for igual a 'Digite um numero...'
        // ele apaga o texto
        // para isso, primeiro, eu preciso pegar o texto escrito no campo
        // e ai, comparar se é igual a 'Digite um numero'
        if ("Digite um numero...".equals(numero.getText())){
        numero.setText("");
        }
    }//GEN-LAST:event_numeroFocusGained

    private void numeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroFocusLost
        if ("".equals(numero.getText())){
            numero.setText("Digite um numero...");
        }
    }//GEN-LAST:event_numeroFocusLost

    private void outroNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_outroNumeroFocusGained
       if ("Digite outro numero...".equals(outroNumero.getText())){
        outroNumero.setText("");
        }
    }//GEN-LAST:event_outroNumeroFocusGained

    private void outroNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_outroNumeroFocusLost
        if ("".equals(outroNumero.getText())){
            outroNumero.setText("Digite outro numero...");
        }
    }//GEN-LAST:event_outroNumeroFocusLost

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        String numero1 = numero.getText();
        String numero2 = outroNumero.getText();  
        double numero1D = Double.parseDouble(numero1);
        double numero2D = Double.parseDouble(numero2);
        
        double dividir = numero1D / numero2D;
        results.setText("Resultado: " + dividir);
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtrairActionPerformed
        String numero1 = numero.getText();
        String numero2 = outroNumero.getText();  
        double numero1D = Double.parseDouble(numero1);
        double numero2D = Double.parseDouble(numero2);
        
        double subtrair = numero1D - numero2D;
                results.setText("Resultado: " + subtrair);
    }//GEN-LAST:event_btnSubtrairActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        String numero1 = numero.getText();
        String numero2 = outroNumero.getText();  
        double numero1D = Double.parseDouble(numero1);
        double numero2D = Double.parseDouble(numero2);
        
        double multiplicar = numero1D * numero2D;
        results.setText("Resultado: " + multiplicar);
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnSomar;
    private javax.swing.JButton btnSubtrair;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField outroNumero;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel results;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
